all:
  vars:
    ansible_user: ansible
    ansible_password: ansible
    ansible_become: true
    ansible_become_method: sudo
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
  children:
    etcd:
      hosts:
        etcd1:
          ansible_host: etcd1
        etcd2:
          ansible_host: etcd2
        etcd3:
          ansible_host: etcd3

